-----
### Checked 예외 기본 이해
-----
1. Exception과 그 하위 예외는 모두 컴파일러가 체크하는 Checked 예외
2. 단, RuntimeException은 예외로 함
3. Checked 예외는 잡아서 처리하거나, 또는 밖으로 던지도록 선언해야 함
4. 그렇지 않으면, 컴파일 오류 발생

-----
### 체크 예외 전체 코드
-----
```java
package hello.jdbc.exception.basic;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThatThrownBy;

@Slf4j
public class CheckedTest {

    @Test
    void checked_catch() {
        Service service = new Service();
        service.callCatch();
    }

    @Test
    void checked_throw() {
        Service service = new Service();
        assertThatThrownBy(() -> service.callThrow())
                .isInstanceOf(MyCheckedException.class);
    }
    /**
     * Exception을 상속받은 예외는 Checked 예외가 됨
     */
    static class MyCheckedException extends Exception {
        public MyCheckedException(String message) {
            super(message);
        }
    }

    /**
     * Checked 예외는 예외를 잡아서 처리하거나, 던지거나 둘 중 하나를 필수로 선택
     */
    static class Service {
        Repository repository = new Repository();

        /**
         * 예외를 잡아서 처리하는 코드
         */
        public void callCatch() {
            try {
                repository.call();
            } catch (MyCheckedException e) {
                // 예외 처리 로직
                log.info("예외 처리, message={}", e.getStackTrace(), e);
            }
        }

        /**
         * Checked 예외를 밖으로 던지는 코드
         * Checked 예외는 예외를 잡지 않고, 밖으로 던지면 throws 예외를 메서드에 필수로 선언
         */
        public void callThrow() throws MyCheckedException {
            repository.call();
        }
    }

    static class Repository {
        public void call() throws MyCheckedException {
            throw new MyCheckedException("ex");
        }
    }
}
```

1. Exception을 상속받은 예외는 Checked 예외가 됨
```java
/**
 * Exception을 상속받은 예외는 Checked 예외가 됨
 */
static class MyCheckedException extends Exception {
    public MyCheckedException(String message) {
        super(message);
    }
}
```

  - MyCheckedException은 Exception을 상속 받음
  - Exception을 상속 받으면, Checked 예외가 됨
  - 참고로, RuntimeException을 상속받으면 Unchecked 예외가 됨
  - 예외가 제공하는 여러 기본 기능이 있는데, 그 중 오류 메세지를 보관하는 기능 존재
  - 이는, 생성자를 통해 해당 기능을 그대로 사용하면 편리

2. 예외를 잡아서 처리하는 코드
```java
@Test
void checked_catch() {
    Service service = new Service();
    service.callCatch();
}
```
  - service.callCatch()에서 예외를 처리했기 때문에 테스트 메서드까지 올라오지 않음
  - 실행 순서 분석
    + test → service.callCatch() → repository.call() [예외 발생, 던짐]
    + test ← service.callCatch() [예외 처리] ← repository.call()
    + test[정상 흐름] ← service.callCatch() ← repository.call()

3. Repository.call()에서 MyCheckedException 예외가 발생하고, 이 예외를 Service.callCatch()에서 잡는 것 확인 가능
```java
public void callCatch() {
    try {
        repository.call();
    } catch (MyCheckedException e) {
        // 예외 처리 로직
        log.info("예외 처리, message={}", e.getStackTrace(), e);
    }
}
```

4. 실행 결과
```
[Test worker] INFO hello.jdbc.exception.basic.CheckedTest - 예외 처리, message=ex 
hello.jdbc.exception.basic.CheckedTest$MyCheckedException: ex at hello.jdbc.exception.basic.CheckedTest$Repository.call(CheckedTest.java:64)
at hello.jdbc.exception.basic.CheckedTest$Service.callCatch(CheckedTest.java:45) 
at hello.jdbc.exception.basic.CheckedTest.checked_catch(CheckedTest.java:14)
```
  - 실행 결과 로그를 보면 첫줄은 우리가 남긴 로그가 그대로 남음
  - 두 번쨰 줄부터 예외에 대한 StackTrace 추가 출력
  - 이 부분은 로그를 남길 때, 로그의 마지막 인수에 예외 객체를 전달해주면, 로그가 해당 예외의 스택 트레이스를 추가로 출력해주는 것
    + log.info("예외 처리, message={}", e.getStackTrace(), e);

5. Checked 예외를 잡아서 처리하는 코드
```java
public void callCatch() {
    try {
        repository.call();
    } catch (MyCheckedException e) {
        // 예외 처리 로직
        log.info("예외 처리, message={}", e.getStackTrace(), e);
    }
}
```
  - Checked 예외를 잡아서 처리하면 catch(...) 를 사용해서 예외를 잡으면 됨
  - MyCheckedException 예외를 잡아 처리

6. catch는 해당 타입과 그 하위 타입을 모두 잡을 수 있음
```java
public void callCatch() {
    try {
        repository.call();
    } catch (MyCheckedException e) {
        // 예외 처리 로직
        log.info("예외 처리, message={}", e.getStackTrace(), e);
    }
}
```

  - catch에 MyCheckedException의 상위 타입인 Exception을 적어주어도 잡을 수 있음
  - catch에 예외를 지정하면 해당 예외와 그 하위 타입 예외를 모두 잡아줌
  - 물론, 정확하게 해당 예외를 잡고 싶다면, catch에 MyCheckedException을 적어주면 됨

7. 예외를 처리하지 않고, 밖으로 던지는 코드
```java
/**
 * Checked 예외를 밖으로 던지는 코드
 * Checked 예외는 예외를 잡지 않고, 밖으로 던지면 throws 예외를 메서드에 필수로 선언
 */
public void callThrow() throws MyCheckedException {
    repository.call();
}
```

  - service.callThrow()에서 예외를 처리하지 않고, 밖으로 던졌기 떄문에 예외가 테스트 메서드까지 올라옴
  - 테스트에서 기대한 것처럼 MyCheckedException 예외가 발생하면 성공으로 처리
  - 실행 순서
    + test → service.callCatch() → repository.call() [예외 발생, 던짐]
    + test ← service.callCatch() [예외 던짐] ← repository.call()
    + test[예외 도착] ← service.callCatch() ← repository.call()

8. Checked 예외를 밖으로 던지는 코드
```java
public void callThrow() throws MyCheckedException {
    repository.call();
}
```
  - 체크 예외를 처리할 수 없을 때, method() throws 예외를 사용해 밖으로 던질 예외를 필수로 지정해야 함
  - 여기서는 MyCheckedException을 밖으로 던지도록 지정

9. Checked 예외를 밖으로 던지지 않은 컴파일 오류 발생
```java
public void callThrow() throws MyCheckedException {
    repository.call();
}
```
  - throws 지정하지 않으면 컴파일 오류 발생
```
Unhandled exception: hello.jdbc.exception.basic.CheckedTest.MyCheckedException
```
  - Checked 예외의 경우 예외를 잡아서 처리하거나 또는 throws를 지정해서 예외를 밖으로 던진다는 선언을 필수로 해줘야 함

10. 참고로 체크 예외를 밖으로 던지는 경우도 해당 타입과 그 하위 타입 모두 던질 수 있음
```java
public void callThrow() throws MyCheckedException {
```
  - throws에 MyCheckedException의 상위 타입인 Exception을 적어주어도 MyCheckedException을 던질 수 있음
  - throws에 지정한 타입과 그 하위 타입 예외를 밖으로 던짐
  - 물론 정확하게 MyCheckedExcpetion만 밖으로 던지고 싶다면, throws에 MyCheckedException을 적어주면 됨

-----
### Checked 에외의 장단점
-----
1. Checked 예외는 예외를 잡아서 처리할 수 없을 때, 예외를 밖으로 던지는 throws 예외를 필수로 선언해야 함
2. 그렇지 않으면 컴파일 오류가 발생
3. 이에 대한 장단점이 동시에 존재
  - 장점 : 실수로 예외를 누락하지 않도록 컴파일러를 통해 문제를 잡아주는 안전한 장치
  - 단점 : 하지만 실제로는 개발자가 모든 체크 예외를 반드시 잡거나 던지도록 처리해야 함
    + 또한, 신경쓰고 싶지 않은 예외까지 모두 챙겨야 함
     
